### ISSUE TITLE
Not able to create profile for overnight times

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#11]
**Describe the bug**
A user can't create a profile for the time night of one day to morning of the next day. For eg 11:00 PM - 7:00AM. On choosing these times the app will show enter a valid time.

**To Reproduce**
1. Open quiet hours.
2. Try to create a new profile for the above time conditions.

**Expected behavior**
The user should be able to create a profile for overnight times and the app should work as expected.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by mouryac9** [comment]
Hey! I'd like to work on this.

**Comment by mouryac9** [comment]
I went through the code, and program doesn't crash when the condition for checking end time is larger than start time is removed. Do you know what happens in this condition?

**Comment by rob729** [comment]
Try to make a profile for say start time: 10:00 PM and end time: 7:00 AM.
A snackbar will be shown saying invalid time and the app won't crash.

**Comment by mouryac9** [comment]
Yes I did that. My question is if I remove the code that checks if the end time is larger than the start time, what will be the apps behavior?

**Comment by mouryac9** [comment]
I'll try it out myself, I guess. If it just moves on to the next day then removing the condition will suffice.

**Comment by rob729** [comment]
@mouryac9 I would also suggest having a look at how workmanager task is created for start and end time.

**Comment by mouryac9** [comment]
Sure. Thanks for the suggestion!

**Comment by mouryac9** [comment]
@rob729 I seem to have found the problem. But for the this issue to be solved, the condition i mentioned above needs to be removed. So, now if someone sets start time as 14:00, end time as 13:00 and selected day is monday, it will just set profile for 2pm on monday till 1pm on tuesday. Should I add a snackbar informing the user of this, so that user can avoid any mistakes? If yes, is there a preferable message format you'd like me to implement?

**Comment by rob729** [comment]
@mouryac9 You can put a check of 12 hrs. I mean if the time difference is more than 12 hours then do not create the profile and show the user a snackbar regarding the same.

**Comment by rob729** [comment]
@mouryac9  Are you a DSC SLoP participant?

**Comment by mouryac9** [comment]
Ok, I'll put that check. And no, I'm not SLoP participant.
