### ISSUE TITLE
Add Contribute.md file

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#15]
Create a Contribute.md file to help new contributors to make a contribution in the project.

**Would you like to work on the issue?**
- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob729 Can I work on this issue?

**Comment by rob729** [comment]
@coder2699 what are you planning to add in this?
I mean in the .md file

**Comment by coder2699** [comment]
@rob729 I am planning to add all the necessary instructions that you have mentioned earlier on the Gitter channel and apart from that some general code of conduct, etc.
Most repositories has such a file, which helps to understand how to contribute to the project.

**Comment by rob729** [comment]
@coder2699 I don't think it is of much use as of now.
You can try finding bugs in the app or suggesting some features instead.
Closing this issue as of now.

**Comment by coder2699** [comment]
> @coder2699 I don't think it is of much use as of now.
> You can try finding bugs in the app or suggesting some features instead.
> Closing this issue as of now.

@rob729 If you think it is required, can you reopen this issue.

**Comment by coder2699** [comment]
> @coder2699 I don't think it is of much use as of now.
> You can try finding bugs in the app or suggesting some features instead.
> Closing this issue as of now.

@rob729 As suggested by you, I have worked on several features/bugs. So can you please reopen this issue and assign it to me.

**Comment by rob729** [comment]
@coder2699 In my above message I have not said after adding several features/bugs, I will reopen this issue. 
It might be helpful for those projects which have a very large codebase and has many new contributors contributing to the project.
I see no point in adding Contribute.md file for quiet hours. 
Instead, focus on fixing any bugs present in the app or suggesting a feature for the app.
