### ISSUE TITLE
UI Revamp

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#16]
**Describe the feature you'd like**
Change the UI of the app. Have a look at the images below to get an idea of what is expected UI.
For the MainFragment, the UI should be almost similar except the dark mode toggle on the action bar is not required to be added in the fix of this issue.
For the NewProfileFragment, try to add an editText which looks visually better and complements the look of the app

**Screenshots**
<img src = "https://user-images.githubusercontent.com/31350501/94960193-12535980-0510-11eb-9f64-8155a1cf2bc3.jpg" width = 200/>  <img src = "https://user-images.githubusercontent.com/31350501/94960195-12ebf000-0510-11eb-8684-1f115940f45a.jpg" width = 200/>

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by JanuKShah** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
@JanuKShah Since @coder2699 claimed the issue before you so I will have to assign him this issue.
In case he decides to work on some other issue instead of this one then I will assign you this issue.

**Comment by rob729** [comment]
@coder2699 Go Ahead
