### ISSUE TITLE
Disable touch on MaterialDayPicker in DetailsFragment

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#17]
**Describe the bug**
A user can click on the MaterialDayPicker shown in the details fragment and can select the days which were not selected initially or unselect the days which they selected.

**To Reproduce**
1. Open Quiet Hours
2. Create a profile.
3. Click on the profile.
4. Click on the MaterialDayPicker shown in the profile.

**Expected behavior**
The user should not be able to change the value of MaterialDayPicker in details fragment.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by JanuKShah** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @JanuKShah

**Comment by rob729** [comment]
@JanuKShah Just want to remind you that after 7 days of assigning the issue if you don't raise a PR then the issue will be unassigned and will be open for others to claim.
