### ISSUE TITLE
Details Fragment not displayed correctly in dark mode

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#18]
**Describe the bug**
The details fragment has not been tuned for the dark mode. The background is shown in white color and the profile title is not shown. 

**To Reproduce**
1. Open Quiet Hours
2. Create a profile.
3. Toggle to the dark mode
4. Click on the profile.

**Expected behavior**
Tune the details fragment accordingly for the dark mode by keeping the background of the bottom sheet black and the color of textviews as white

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by JanuKShah** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
I would suggest you read all the instructions given by me on the Gitter channel.
You can't claim two or more issues at a time. Solve one then claim next.

**Comment by JanuKShah** [comment]
@rob729 Yes, I will keep that in consideration from now on.

**Comment by FirePing32** [comment]
Adding a `:dark` styling can fix this @rob729 . I have already implemented this earlier in an app. I have read the instructions. Can I start creating pr ?

**Comment by rob729** [comment]
@prakhargurunani I would recommend waiting till issue #16 is fixed as PR for the same has been raised and it also UI related change.
BTW are you a DSC SLoP participant?

**Comment by FirePing32** [comment]
> @prakhargurunani I would recommend waiting till issue #16 is fixed as PR for the same has been raised and it also UI related change.
> BTW are you a DSC SLoP participant?

Ok...
I just saw your repo in trending section. Not a DSC SLoP participant.

**Comment by rob729** [comment]
Okay @prakhargurunani
