### ISSUE TITLE
Add timestamp to the profile

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#2]
**Describe the feature you'd like**
Add the time of creation below the profile name as shown in the below image.

**Screenshots**
<img src = "https://user-images.githubusercontent.com/31350501/72205008-572bf180-34a4-11ea-96fe-b2cae6f1c904.png" height = 180>

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: open for all

**Comment by Anshul1507** [comment]
Will surely work!

**Comment by rob729** [comment]
Go Ahead

**Comment by Haid-Faiz** [comment]
Hi Robin Bhaiya.... Firstly i will try to solve this issue of timestamp.

**Comment by rob729** [comment]
Go Ahead @Haid-Faiz

**Comment by Haid-Faiz** [comment]
@rob729  i added timestamp feature

**Comment by coder2699** [comment]
@rob729 if this issue is not getting solved, can I try it once?

**Comment by rob729** [comment]
No.
@Haid-Faiz Has already solved this issue and is currently facing issues in squashing commits.
