### ISSUE TITLE
Repeat Weekly feature

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#20]
**Describe the feature you'd like**
Currently, when a user creates a profile it is active for only one week and after that, it does not work.
A Repeat weekly toggle should be present in NewProfileFragment which should allow the user to repeat the profile for consecutive weeks till they decide to stop it by deleting it.

**Screenshots**
![scrnli_05_10_2020_01-46-05](https://user-images.githubusercontent.com/31350501/95026127-b245ea00-06ac-11eb-8e9b-8962584ad386.png)

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all.

**Comment by coder2699** [comment]
@rob729 I want to claim this issue.

**Comment by rob729** [comment]
Go Ahead @coder2699
