### ISSUE TITLE
Currently active Profile

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#21]
**Describe the feature you'd like**
On the home screen, the app should show currently active profile in case if any profile is active at that moment otherwise nothing is required.
It should be shown just below the action bar.
Try to keep UI/UX in mind while designing it so that it looks good and complements the look of the app.
Also, show till what time the profile will remain active.

**Additional context**
Feel free to discuss how the UI part should look with me in case of any doubts.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699

**Comment by coder2699** [comment]
@rob729 Regarding UI i was thinking of going on with the below design. Hiding the visibility when no profile is active, and when any profile is active it's visible like shown below. 

<img src="https://user-images.githubusercontent.com/61552810/95664992-f718c780-0b69-11eb-8f97-f968aba401ac.png" width="200px" height="400px"/>

If you want me to go with any other design, do let me know.

**Comment by rob729** [comment]
I was thinking of having a card view on the top and inside it, you can show the Active Profile Name and till what time it will be active.
Also, you can add the silent/vibrate mode icon in the card view.

**Comment by coder2699** [comment]
> I was thinking of having a card view on the top and inside it, you can show the Active Profile Name and till what time it will be active.
> Also, you can add the silent/vibrate mode icon in the card view.

Okay, I think I can implement that.

**Comment by coder2699** [comment]
@rob729 i have implemented this. If the UI is fine I will open a PR. If you want any changes, please let me know.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/61552810/95686592-66e78a80-0c1c-11eb-80ee-7fe063eaf4b6.png" width="200px" height="400px"/></td>
<td><img src="https://user-images.githubusercontent.com/61552810/95686593-66e78a80-0c1c-11eb-9071-d6149f505228.png" width="200px" height="400px"/></td>

<td><img src="https://user-images.githubusercontent.com/61552810/95686591-664ef400-0c1c-11eb-88b8-8dcf59480616.png" width="200px" height="400px"/></td>

</tr>
</table>)

**Comment by rob729** [comment]
@coder2699 It looks good to me. Please raise PR.
Also, once try to add "currently" before active, and if it looks good then add it also in the PR.

**Comment by coder2699** [comment]
> @coder2699 It looks good to me. Please raise PR.
> Also, once try to add "currently" before active, and if it looks good then add it also in the PR.

Should I upload a ss with "currently" added? Only concern is, if profile name is long, it will take more space.

**Comment by rob729** [comment]
You can decrase the text size little bit. Also try it with a long profile name if it is shown in multi lines or not.

**Comment by coder2699** [comment]
> You can decrase the text size little bit. Also try it with a long profile name if it is shown in multi lines or not.

Done, working fine
