### ISSUE TITLE
Add Silent/Vibrate mode selector

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#22]
**Describe the feature you'd like**
Currently, the app has a Silent/Vibrate mode selector in the settings option. It needs to be shifted to NewProfileFragment to allow users to select the mode individually for each profile.
Detail fragment should show the mode selected by the user.
Keep the default value to vibrate.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue.

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699
