### ISSUE TITLE
Fix UI for Screens Where Required (Landscape Mode)

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#26]
**Describe the bug**
For some screens UI in the Landscape mode is not as expected. Also, action bar title is not at center in Landscape mode. 

**Screenshots**

<img src="https://user-images.githubusercontent.com/61552810/95354325-e9511100-08e1-11eb-90cf-c5be1e14330e.png" width="450px" height="225px">
<img src="https://user-images.githubusercontent.com/61552810/95354331-ea823e00-08e1-11eb-8f73-da2b2aaf5422.png" width="450px" height="225px">

<img src="https://user-images.githubusercontent.com/61552810/95354340-ed7d2e80-08e1-11eb-84f6-13825a073009.png" width="450px" height="225px">

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob729 Shall I work on it?

**Comment by rob729** [comment]
@coder2699 Go Ahead

**Comment by coder2699** [comment]
@rob729 ok. Can you please add labels for difficulty and SLoP points
