### ISSUE TITLE
User Interface  Improvement

### ISSUE THREAD

**Issue by Haid-Faiz** [rob729/Quiet_Hours#30]
**UI Improvements:**

- Currently in MainFragment when there is no profile present, it shows a png image, So, we can replace that image with some 
good Lottie Animation that will improve UI & UX.
- Currently icon at splash screen is png image (which is looking little bit blur/faddish), we can replace it with other svg image which will look clear.
- Currently color of status bar in Splash screen is black (with white texts in it), So, we can change status bar color to white with black color texts in it.

**Screenshots of current state**

![Screenshot_20201010-162017_Quiet_Hours 1](https://user-images.githubusercontent.com/56159740/95653246-f4d84e00-0b14-11eb-84bb-4ac78f04be1b.jpg)

![Screenshot_20201010-162045_Quiet_Hours 1](https://user-images.githubusercontent.com/56159740/95653260-12a5b300-0b15-11eb-892b-6ddfbeb21091.jpg)

**Would you like to work on the issue ?**
- [x] Yes
- [ ] No
- Other:

**Comment by Haid-Faiz** [comment]
@rob729  if you will approve this issue then i want to work on it...

**Comment by rob729** [comment]
@Haid-Faiz Can you share the Lottie animation you are planning to add in the app?
Regarding the rest two points, definitely, we can make those changes.

**Comment by Haid-Faiz** [comment]
@rob729  i am thinking to add this..... with the tag  ***Relax ! No profile added*** https://lottiefiles.com/25931-time-to-relax

also have a look at this https://lottiefiles.com/15268-notification & this https://lottiefiles.com/4599-notificacion

if these are not suitable then kindly you suggest some

**Comment by rob729** [comment]
https://lottiefiles.com/29488-note-icon.
You can this animation.

**Comment by Haid-Faiz** [comment]
@rob729  Kindly assigned it to me...

**Comment by rob729** [comment]
Go Ahead @Haid-Faiz

**Comment by Haid-Faiz** [comment]
@rob729 i am using windowLightStatusBar attribute in styles.xml to make status bar text color to black but as this attribute is only allowed using in api level >=23 & current api level is below 23, So, how can i solve this problem in current api level.

OR should i use ***tools:targetApi***  like:       ***item name="android:windowLightStatusBar" tools:targetApi="m">true***

**Comment by Haid-Faiz** [comment]
@rob729  One more doubt...!  When we use this way...

**window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR**
