### ISSUE TITLE
Fix Vibration Mode

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#34]
**Describe the bug**
When a user has made two profiles A(10:00 AM - 12:00 PM) and B(11:00 AM - 1:00 PM) for the same day then at 12:01 PM, when profile A ends the phone audio profile changes to Normal. But instead it should switch the audio profile as set for profile B. 

**Expected behavior**
According to above given scenario, at 12:01PM, the phone audio settings should be same as set in profile B.  

- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
@coder2699 Go Ahead
