### ISSUE TITLE
Add Clear All profile feature

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#36]
**Describe the feature you'd like**
If a user has 7-8 profiles and wishes to delete all profiles, he has to swipe each and click "yes" for all 7-8 alert dialog box

Add a clear all feature such that when user selects it, all the created profiles are deleted. An alert dialog box must appear to confirm yes or no. 
If no profile is present and user selects delete all, then a snackbar must appear saying "no profile is present"

**Would you like to work on the issue?**
- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to ask, shall I add separate button for it or shall I add an item in overflow menu?

**Comment by rob729** [comment]
> @rob729 I want to ask, shall I add separate button for it or shall I add an item in overflow menu?

add in overflow menu.
