### ISSUE TITLE
Update Screenshots in Readme.md 

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#39]
**Describe the chore**
Due to the following changes in the application, readme.md must be updated with fresh screenshots:-
<ul>
<li>Addition of Vibration state icon in details fragment</li>
<li>Addition of timestamp in MainFragment</li>
<li>Addition of Currently Active Profile Card</li>
</ul>

**Would you like to work on the issue?**
- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
@coder2699 Not required as of now. I would open this issue at a later point in time after a significant contribution to the app.
