### ISSUE TITLE
Store the color of AvatarImageView

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#4]
**Describe the feature you'd like**
Currently, the color of AvatarImageView gets change every time when the view is recreated. So for every profile assign a color by picking up a color randomly from the list of colors(which is already present in code), store it in the database and set that color to the AvatarImageView.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729  Please assign this to me. I can fix it and would like to work on it.

**Comment by rob729** [comment]
@coder2699 If you want the contribution to be considered in SLoP, then you will have to wait as the coding period will start from 28th Sept.

**Comment by coder2699** [comment]
@rob729 thanks for responding. I will wait till the coding period starts.

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699

**Comment by rob729** [comment]
give @coder2699 75 points
