### ISSUE TITLE
Background color inconsistency in dark mode

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#40]
**Describe the bug**
In dark mode, the background color of the settings page is different from the normal background of the app.

**To Reproduce**
1. Open the app.
2. Turn on dark mode.
3. Open settings.

**Expected behavior**
Find the color code of the settings page background in dark mode and use it as the background color for the app in dark mode

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by Haid-Faiz** [comment]
@rob729 i want to claim this issue..

**Comment by rob729** [comment]
Go ahead @Haid-Faiz
