### ISSUE TITLE
Remove Active Profile when a Profile is deleted

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#43]
**Describe the bug**
When a profile is active, and the user deletes it by swiping or deletes all profiles, still the currently active profile card remains present.

**To Reproduce**
1. Wait for a profile to be active
2. When it is active, delete it
3. Observe that currently active profile remains as it is.

**Expected behavior**
When all profiles are deleted then no profile is active, so it shouldn't be shown as active

**Screenshots**
<img src="https://user-images.githubusercontent.com/61552810/97085568-e2453500-163b-11eb-8b2f-fd6a611aae8e.png" width="240px" height="480px">

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other:

**Comment by coder2699** [comment]
@rob729 I want to claim this issue.

**Comment by rob729** [comment]
Go Ahead @coder2699
