### ISSUE TITLE
Dark mode bug

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#45]
**Describe the bug**
When the system dark mode is active on a device and the user opens the app after installing it then the status bar text color is black and the background color is also dark.

**To Reproduce**
1. Enable dark mode on android device.
2. Install the app.
3. Open the app.
4. Give permissions.
5. Go back to the app.

**Expected behavior**
The app should set the value of dark mode according to the system. If the system dark mode is enabled then the app should enable dark mode automatically and the value of shared preference of dark mode should also be changed accordingly.
This has to be done only when the app is opened for the first time.

**Screenshots**
<img src = "https://user-images.githubusercontent.com/31350501/97140104-f3985980-1781-11eb-825a-c8bc0d3ea687.jpg" width = "250"/> <img src = "https://user-images.githubusercontent.com/31350501/97140377-7b7e6380-1782-11eb-9cd3-c49abad72eb5.jpg" width = "250"/>

**Smartphone Info:**
Android version: Android 10

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to try to fix this issue.

**Comment by rob729** [comment]
@coder2699 Go Ahead

**Comment by coder2699** [comment]
@rob729 as mentioned by you "This has to be done only when the app is opened for the first time.", does it mean that when the app installs only then? or whenever the user opens the app after killing it?

**Comment by rob729** [comment]
App installs/App data reset.
