### ISSUE TITLE
App Intro

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#46]
**Describe the feature you'd like**
Currently, the app is using MaterialIntroView to tell the users about the features of the app. 
Now a view pager has to be shown in which various functionality of the app has to be shown to the user.
You can use this library to implement the same: https://github.com/AppIntro/AppIntro

**Additional context**
All the features highlighted using material intro view have to be shown in the view page based intro as well.
Remove the material intro view after adding this feature.
Values to be assigned when implementing the library(Have a look at documentation, you will get to know about these attributes):
Slide Transformer = AppIntroPageTransformerType.SlideOver
Wizard mode = true
Enabe ImmersiveMode
Also ask for "Do not distrub" permission in the intro itself. See the documentation, resources for permission are present there.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by Haid-Faiz** [comment]
@rob729 i want to try this issue...

**Comment by rob729** [comment]
Go Ahead @Haid-Faiz

**Comment by Haid-Faiz** [comment]
@rob729 For making of slides... Should i make fragments & pass to addSlide() or should i use pre built fragment provided by AppIntro library itself...??

**Comment by Haid-Faiz** [comment]
@rob729  & should i add skip button to it...??

**Comment by rob729** [comment]
> @rob729 For making of slides... Should i make fragments & pass to addSlide() or should i use pre built fragment provided by AppIntro library itself...??

You can use the pre build fragments. Just keep in mind that it looks visually good and delivers the information to the user correctly.

**Comment by rob729** [comment]
> @rob729 & should i add skip button to it...??

Yes add the skip button.

**Comment by rob729** [comment]
@Haid-Faiz Any updates?

**Comment by Haid-Faiz** [comment]
@rob729 Sorry for delay.... actually i was busy in something other.
By the way i have added appIntro... adding permission is left...
I will try to generate PR today

**Comment by Haid-Faiz** [comment]
@rob729  do i also need to add screenshots of Old Intro....??

i am doing like this:
- 1)  Welcome to Quiet Hours......    *Schedule silent mode automatically*

- 2)  Detail about old intro....

- 3)  About night mode

**Comment by rob729** [comment]
On the first screen make it:-
Welcome to Quiet Hours
No more trouble to make silent mode ON/OFF manually every time.
after that, you have to show the screenshot and the text of the features which are currently shown in the app when a user installs the app for the first time like the delete feature, details feature. No need to tell about night mode though.

**Comment by Haid-Faiz** [comment]
> On the first screen make it:-
> Welcome to Quiet Hours
> No more trouble to make silent mode ON/OFF manually every time.
> after that, you have to show the screenshot and the text of the features which are currently shown in the app when a user installs the app for the first time like the delete feature, details feature. No need to tell about night mode though.

@rob729  Ok, I am also facing difficulties in asking permission...
 For checking...  I only call askForPermissions() method provided by appIntro... buy that runtime permission dialog didn't come.

Do i also need to override onRequestPermissionResult() method.

**Comment by rob729** [comment]
Actually, I have not used this library on a project so I can't give you an answer. You will have to go through the documentation of the library to know more.

**Comment by Haid-Faiz** [comment]
@rob729  i have gone through the documentation but after writing the code, still it isn't working means it's not requesting the runtime permission. kindly check it... (do i need to override some other methods like onRequestPermissionResult(), etc).

**Comment by rob729** [comment]
Okay. 
Then don't ask permission in the app intro

**Comment by rob729** [comment]
@Haid-Faiz I have updated the points associated with this issue.
