### ISSUE TITLE
Restore system audio when active profile is deleted

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#49]
**Describe the bug**
When an active profile is deleted, the ringtone mode remains to be in vibration/silent state. Fix this, so that when an active profile is deleted ringtone mode becomes normal.

**Would you like to work on the issue?**
Yes

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
@coder2699 Go Ahead.
You have to set it to the previous state. Eg; if the device was in a vibrate state before the profile got activated then after deleting the active profile it should be restored to vibrate state.

**Comment by coder2699** [comment]
@rob729 if i store the previous state as sharedpref will it be ok? So that while deleting I can set it back to previous state
