### ISSUE TITLE
Replace DetailsFragment by Bottom sheet

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#5]
**Describe the feature you'd like**
Replace the details fragment by a bottom sheet to show the details of a profile.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699

**Comment by rob729** [comment]
give @coder2699 75 points
