### ISSUE TITLE
Add ViewBinding in the app

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#51]
**Describe the feature you'd like**
Currently, the app uses DataBinding in the app. Implement the ViewBinding in place of it and remove the DataBinding code.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699
