### ISSUE TITLE
Fix UI Bugs

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#53]
,**Describe the bug**
<ul>
<li>The Avtar icon is not centrally placed and does not looks nice when profile name is of multiple lines. Fix it.</li>
<img src="https://user-images.githubusercontent.com/61552810/98076142-b4f65380-1e93-11eb-8697-23999355bacc.png"
 width="300px" height="200px"/>
<li>When profile name is of multiple lines, the vibrator icon and Repeat Weekly icon doesn't appear. Change the position of these icons in Details fragment after discussing it with @rob729 .</li>
<img src="https://user-images.githubusercontent.com/61552810/98075936-503af900-1e93-11eb-9981-393b7b9c79e4.png" width="200px" height="200px"/>
<li>The color of  vibrator and silent icon is completely different from rest of the color scheme, which doesn't looks good. Change color of vibrator and silent icon to accent color.</li>
<img src="https://user-images.githubusercontent.com/61552810/98075931-4dd89f00-1e93-11eb-81ed-cdc3f5d003ef.PNG"/>
</ul>

**Would you like to work on the issue?**
-  Yes

**Comment by coder2699** [comment]
@rob729 if you approve this issue, please tell where shall vibrator icon and Repeat Weekly icon be placed.

**Comment by rob729** [comment]
Go Ahead @coder2699.
Center align the profile name. The icons should be placed below the textview and the layout holding the icons should be center aligned.
Also, choose a better-looking icon for silent mode.
