### ISSUE TITLE
End Time format on Currently Active Profile

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#59]
**Describe the bug**

Format of End time in Currently Active Card does not looks good in certain cases. For example, if time is 00:05, then in the card it gets displayed as 0:5 . Fix this such that in active card end time is displayed as 00:05

**Screenshots**
<img src="https://user-images.githubusercontent.com/61552810/99564723-cd688100-29f0-11eb-9a11-0ffb675309ad.png" width="300px" height="200px"/>

**Comment by coder2699** [comment]
@rob729 I want to work on this issue, if you approve it

**Comment by rob729** [comment]
Go Ahead @coder2699 
There is a function that performs the above task while assigning the text to start/end time editText. Move that function to Utils.kt and reference that function from Utils.kt
