### ISSUE TITLE
Change the permission request message

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#6]
**Describe the feature you'd like**
Currently, the app requests the user for Do Not Disturb access permission for the app to work properly.
Change the permission request message to "Please give the Do Not Disturb access permission for the app to work properly. Click OK to continue."
I have added the screenshot of the permission request which is to be changed. 

**Screenshots**
<img src = "https://user-images.githubusercontent.com/31350501/72675694-28b6a380-3aae-11ea-8fd2-208a5e4054f8.png" width = 250>

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all.

**Comment by fredunit** [comment]
I have changed the request message, but which emulator can i open the app and capture the screenshot like you?

**Comment by rob729** [comment]
You can use the Android device emulator present in the Android studio or you can install the app on a physical Android phone if you have one.
Also remember to first claim an issue before working on an issue.

**Comment by fredunit** [comment]
I would like to claim #6 Change the permission request message.
Should I create a new Button tag to make the change?

**Comment by rob729** [comment]
You have to just change the message of alert dialog.
What do you mean by the Button tag?

**Comment by coder2699** [comment]
@rob729 Is the issue still open? I would like to work on it. If it is available, please assign it to me.

**Comment by coder2699** [comment]
@rob729 I want to claim this issue.

**Comment by rob729** [comment]
Go Ahead @coder2699

**Comment by rob729** [comment]
give @coder2699 5 points
