### ISSUE TITLE
Material Day picker width is getting cropped on wider screens (ex. 1080p resolution)

### ISSUE THREAD

**Issue by Haid-Faiz** [rob729/Quiet_Hours#62]
**Describe the bug**
- Currently in profile detail bottom sheet, Day picker width is getting cropped on mobiles of wider screen resolution like 1080p (ex. galaxy j7 prime)

**To Reproduce**
- Steps to reproduce the behavior:
1. Go to fragments_details.xml
2. Remove start & end margins of day picker.

**Screenshots**

<img src = "https://user-images.githubusercontent.com/56159740/99876477-ebb2c480-2c1c-11eb-96f1-da09cba19749.jpg" height = "480" width="280">

**Expected behavior**
- Material Day picker width shouldn't be cropped on screens like 1080p of width

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- [ ] Other:

**Comment by Haid-Faiz** [comment]
@rob729 i want to fix it...

**Comment by rob729** [comment]
@Haid-Faiz You can work on this issue if you want to.

**Comment by Haid-Faiz** [comment]
@rob729 i'll generate the PR till evening

**Comment by rob729** [comment]
Cool :thumbsup:
