### ISSUE TITLE
Allow user to add some description/short notes

### ISSUE THREAD

**Issue by coder2699** [rob729/Quiet_Hours#63]
**Describe the feature you'd like**
Add a checkbox in NewProfileFragment, if checked allow the user to add some short note/ description/ key points and display it in the details fragment
If not checked, app should work in current state. 

**Screenshots**

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/61552810/99883084-f4ba8a80-2c4a-11eb-8b10-a3220b6e2a84.png" height="400px" width="200px"/></td>
<td><img src="https://user-images.githubusercontent.com/61552810/99883086-f6844e00-2c4a-11eb-885d-1d9b16b7c564.png" height="400px" width="200px"/></td>
</tr>
</table>

**Would you like to work on the issue?**

- [x] Yes

**Comment by rob729** [comment]
@coder2699 Go Ahead

**Comment by coder2699** [comment]
@rob729 will you consider increasing the points,? If you feel apt, otherwise no problem.

**Comment by coder2699** [comment]
Also, do you want the notes to be displayed in Details Fragment only? or even in the MainFragment Profile card also...below the title?

**Comment by rob729** [comment]
> Also, do you want the notes to be displayed in Details Fragment only? or even in the MainFragment Profile card also...below the title?

Details Fragment below the profile name.

**Comment by rob729** [comment]
> @rob729 will you consider increasing the points,? If you feel apt, otherwise no problem.

IMO this is a simple feature and the currently assigned points are good enough.
At a later point in time, if I feel that the points assigned are less then I will update it.
