### ISSUE TITLE
Update Screenshots in Readme.md

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#64]
**Describe the chore**
A decent number of bug fixes and features have been added since so time to update the screenshots in the readme file.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by coder2699** [comment]
@rob729 Can I take up this task now?

**Comment by rob729** [comment]
Go Ahead @coder2699
