### ISSUE TITLE
Add a profile pause/resume feature

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#7]
**Describe the feature you'd like**
The user should be able to pause/resume any profile.

**Screenshots**
![scrnli_24_09_2020_00-57-28](https://user-images.githubusercontent.com/31350501/94060102-01fcf980-fe01-11ea-9523-cf6f4f894b96.png)

**Additional context**
Make sure that the app works as expected when a profile is resumed/paused.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by prakhargurunani** [comment]
Hey @rob729 I can also work on this issue. May I go ahead ?

**Comment by rob729** [comment]
Go Ahead @prakhargurunani

**Comment by coder2699** [comment]
@rob729 I think I have resolved this issue, can I claim it?

**Comment by rob729** [comment]
Go ahead @coder2699
