### ISSUE TITLE
Add Snackbar when a profile is paused/resumed

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#72]
**Describe the feature you'd like**
Add a snackbar whenever the user pauses or resumes a profile.
Message to be shown: "Profile Name" is Paused/Resumed
Snackbar time: Short

Note: You cannot pass/store the view reference from MainFragment in the profileListAdapter. 

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I want to claim this issue

**Comment by rob729** [comment]
Go Ahead @coder2699
