### ISSUE TITLE
Improve project maintainability

### ISSUE THREAD

**Issue by rob729** [rob729/Quiet_Hours#73]
**Describe the chore**
Improve the project maintainability by fixing the issues mentioned in the given link: https://codeclimate.com/github/rob729/Quiet_Hours/issues
You get 25 points for every 8 issues fixed in a PR.
Also mentioned every issue fixed in the PR description.

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Open for all

**Comment by coder2699** [comment]
@rob729 I would like to fix these errors
